#+TITLE: History of Civilization Notes

* 20200121
- Portugeuse really good at sailing
- Africans viewed the Portugeuse and Europeans as conquorers, sailors, and christians.
- The Columbus Exchange (1492) brought many things
- Today most people live in _Nation States_
- Circa 1400 most people lived in _Empire_
* 20200123
- *Creolization*: a historical process by which cultures, religions and languages emerged from contact between various groups, usually in contexts in which Europeans conquered, settled or set up trading posts abroad
- Americas: Native Americans, Europeans, and Africans
- The Three Mulato of Es Miralda
  - Painting from Ecuador
  - Africans dressed as high class europeans
- Arkansas was a French territory
- Spanish dominated as a European power
- Sartorial expression: clothing expression
- European culture blended into the Americas
- Syncretic Culture: The active blending, syncronizing, and relating of cultures and religion.
  - AKA Syncretism
  - for the purpose of Europe into the Americas, this is blending the catholic religion with the pagans.
  - Europeans used appropriate symbols to convince conversion, "you have gods, we have saints just one God to rule them all
- Creolization occured in Africa as well, especially in the Kongo
- Best way to convert a nation is to convert the king
- Fench forged connections with the Indians to compete with Britain
- Mestizzo = white + indian
- Blended hierarchy:
  - Indios
  - Castas
  - Criollos
  -
- Creols
** Quiz
1. Circa 1600 who controlled the most american territories
   - Spanish
2. Our Lady Guadalupe is from where?
   - Mexico
3. ______ Is the mixing of two or more beief systems into a new system
   - Syncretism
4. According to Strayer and Nelson the "three C's" of contextual thinking in world history are 1) 2) 3)_____
   - Comparison
5. The literal meaning of a Creole Person is
   - ... A person born in a European-colonial space in the americas or elsewhere of any racial background
6. 15th centure, Ming emporer gift giraffe
   - True
7. Most of the world lives in nation states
   - True
8. Long question [Read Carefully]
   - Slavery was a feature of society in New Spain, but not in New England
9. In the late 5th century, the period known s teh "Reconquista" wrapped up, ending centuries of Muslim rule in Spain
   - True
10. Although less numerous than the Amerindians, the Spanish were able to conquer Mexico and carve out...
    - Amerindians did not have cities and Infrastructure, like Europeans
11. Who were the "Castas"
    - Categories of Mixed race people
12. Before the arriva of Europeans, the two most powerful and most populus empres
    - Inca and Aztec
13. The documents concerning the encounter between the last Aztex empror Montezuma
    - True
14. The Columbian Exchange refers to the massive transfer of people, plants, animals, and microbes between f
    - Potatoes
