#+TITLE: STAT 3352 Homework Chapter 2
#+AUTHOR: Denver Ellis
#+OPTIONS: tex:t
#+LaTeX_COMPILER: pdflatex

* Problem 1
** Question
A family consisting of three persons—A, B, and C—goes to a medical clinic that always has a doctor at each of stations 1, 2, and 3. During a certain week, each member of the family visits the clinic once and is assigned at random to a station. The experiment consists of recording the station number for each member. One outcome is (1, 2, 1) for A to station 1, B to station 2, and C to station 1.

- List the 27 outcomes in the sample space.
- List all outcomes in the event that all three members go to the same station.
- List all outcomes in the event that all members go to differentstations.
- List all outcomes in the event that no one goes to station 2.
** Answer
* Problem 2
** Question
A mutual fund company offers its customers a variety of funds: a money-market fund, three different bond funds (short, intermediate, and long-term), two stock funds (moderate and high-risk), and a balanced fund. Among customers who own shares in just one fund, the percentages of customers in the different funds are as follows: Money-market 20%, High-risk stock 18%, Short bond 15%, Moderate-risk stock 25%, Intermediate bond 10%, Balanced 7%, Long bond 5%.

 A customer who owns shares in just one fund is randomly selected.

- What is the probability that the selected individual owns shares in the balanced fund?
- What is the probability that the individual owns shares in a bond fund?
- What is the probability that the selected individual does not own shares in a bond fund?
** Answer
* Problem 3
** Question
A box contains six 40-W bulbs, five 60-W bulbs, and four 75-W bulbs. If bulbs are selected one by one in random order, what is the probability that at least two bulbs must be selected to obtain one that is rated 75 W?
** Answer
* Problem 4
** Question
A box in a certain supply room contains four 40-W lightbulbs, five 60-W bulbs, and six 75-W bulbs. Suppose that three bulbs are randomly selected.

- What is the probability that exactly two of the selected bulbs are rated 75-W?
- What is the probability that all three of the selected bulbs have the same rating?
- What is the probability that one bulb of each type is selected?
** Answer
* Problem 5
** Question
Suppose an individual is randomly selected from the population of all adult males living in the United States. Let A be the event that the selected individual is over 6 ft in height, and let B be the event that the selected individual is a professional basketball player. Which do you think is larger, P(A|B) or P(B|A) ? Why?
** Answer
* Problem 6
** Question
The population of a particular country consists of three ethnic groups. Each individual belongs to one of the four major blood groups. The accompanying joint probability table gives the proportions of individuals in the various ethnic group–blood group combinations.

Blood Group:
| Ethnic Group |     O |     A |     B |    AB |
|--------------+-------+-------+-------+-------|
|            1 | 0.082 | 0.106 | 0.008 | 0.004 |
|            2 | 0.135 | 0.141 | 0.018 | 0.006 |
|            3 | 0.215 | 0.200 | 0.065 | 0.020 |

Suppose that an individual is randomly selected from the
population, and define events by A=type A selected, B=type B selected
and C= ethnic group 3 selected.

- Calculate P(A), P(C), and .P(A and C)
- Calculate both P(A|C) and P(C|A), and explain in context what each of these probabilities represents.
- If the selected individual does not have type B blood, what is the probability that he or she is from ethnic group 1?
** Answer
* Problem 7
** Question
The proportions of blood phenotypes in the U.S. population are as follows:

|   A |   B |  AB |   O |
|-----+-----+-----+-----|
| .40 | .11 | .04 | .45 |

Assuming that the phenotypes of two randomly selected individuals are independent of one another, what is the probability that both phenotypes are O? What is the probability that the phenotypes of two randomly selected individuals match?
** Answer
* Problem 8
** Question
Seventy percent of all vehicles examined at a certain emissions inspection station pass the inspection. Assuming that successive vehicles pass or fail independently of one another, calculate the following probabilities:
- P(all of the next three vehicles inspected pass)
- P(at least one of the next three inspected fails)
- P(exactly one of the next three inspected passes)
- P(at most one of the next three vehicles inspected passes)
- Given that at least one of the next three vehicles passes inspection, what is the probability that all three pass (a conditional probability)?
** Answer
